class ParseError(Exception):
    """Base for recoverable parse failures. reason is user-facing."""
    def __init__(self, reason: str):
        super().__init__(reason)
        self.reason = reason


class EncryptedFileError(ParseError): ...
class CorruptFileError(ParseError): ...
class NoExtractableTextError(ParseError): ...
class EmptyDocumentError(ParseError): ...
class UnsafeArchiveError(ParseError): ...
