#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# EasyNotes — package the project into a portable zip for moving to another box.
# EXCLUDES: .venv (458 MB, regenerated by `make setup`), .env (secrets), data/*
# (flushed — the app recreates it and re-seeds on demand), caches, model cache.
# INCLUDES: the full .git history, so you can `make github-push` from the new box.
# On the new machine:  unzip easynotes.zip -d easynotes && cd easynotes && make setup
#   Override output path:  OUT=/path/to/easynotes.zip bash scripts/package.sh
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

OUT="${OUT:-dist/easynotes.zip}"
command -v zip >/dev/null 2>&1 || { echo "ERROR: 'zip' not found." >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
rm -f "$OUT"

echo "==> packaging project → $OUT"
echo "    excluding: .venv, .env, data/, caches, models/  |  including: .git history"
zip -rq "$OUT" . \
  -x '.venv/*' \
  -x '.env' \
  -x 'data/*' \
  -x '*__pycache__*' \
  -x '*.pyc' \
  -x '.pytest_cache/*' \
  -x '.coverage' \
  -x 'htmlcov/*' \
  -x 'dist/*' \
  -x 'models/*' \
  -x 'push_all.sh' \
  -x '*.DS_Store'

git_entries="$(unzip -l "$OUT" | grep -c '\.git/' || true)"
echo "==> done"
echo "    size:        $(du -h "$OUT" | cut -f1)"
echo "    .git entries: ${git_entries} (history travels with the zip)"
echo "    .env present: $(unzip -l "$OUT" | grep -qE ' \.env$' && echo 'YES (BUG!)' || echo 'no — secrets excluded')"
